=== Ivonneperezf/NovenoSemestre/WebSemantica/Ejercicios/VersionesConXSD/playlist/musica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- Elemento raíz -->
    <xs:element name="playlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cancion" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Canción -->
    <xs:element name="cancion" type="cancionType"/>

    <!-- Tipo base de canción -->
    <xs:complexType name="cancionBaseType">
        <xs:sequence>
            <xs:element ref="interpretes"/>
            <xs:element ref="compositores"/>
            <xs:element ref="letristas"/>
        </xs:sequence>
        <xs:attribute name="nombre" type="xs:string" use="required"/>
        <xs:attribute name="duracion" type="xs:string" use="required"/>
        <xs:attribute name="genero" type="xs:string" use="required"/>
        <xs:attribute name="album" type="xs:string" use="required"/>
        <xs:attribute name="aniolanzamiento" type="xs:gYear" use="required"/>
    </xs:complexType>

    <!-- Canción con extensión (herencia) -->
    <xs:complexType name="cancionType">
        <xs:complexContent>
            <xs:extension base="cancionBaseType">
                <xs:attribute name="idioma" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Interpretes -->
    <xs:element name="interpretes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="interprete" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Persona base (herencia) -->
    <xs:complexType name="personaBaseType">
        <xs:sequence>
            <xs:element ref="nombre"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Interprete hereda de persona -->
    <xs:complexType name="interpreteType">
        <xs:complexContent>
            <xs:extension base="personaBaseType">
                <xs:sequence>
                    <xs:element ref="alias" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="interprete" type="interpreteType"/>

    <!-- Compositores -->
    <xs:element name="compositores">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="compositor" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="compositorType">
        <xs:complexContent>
            <xs:extension base="personaBaseType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="compositor" type="compositorType"/>

    <!-- Letristas -->
    <xs:element name="letristas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="letrista" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="letristaType">
        <xs:complexContent>
            <xs:extension base="personaBaseType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="letrista" type="letristaType"/>

    <!-- Elementos simples -->
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="alias" type="xs:string"/>

</xs:schema>

=== Ivonneperezf/NovenoSemestre/WebSemantica/Ejercicios/XML, DTD, XSD, XSL/playlist/XSD,XSL/musica.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="musica.xsl"?>
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="musica.xsd">
    <!-- cancion 1 -->
    <cancion nombre="dime" duracion="3:55 min" genero="folk" album="ultrasodade" aniolanzamiento="2025">
        <interpretes>
            <interprete>
                <nombre>Kevin Eduardo</nombre>
                <alias>Kevin Kaarl</alias>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Kevin Eduardo Hernandez Carlos</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Kevin Eduardo Hernandez Carlos</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 2 -->
    <cancion nombre="Pelicula" duracion="3:35 min" genero="rock" album="memoria futuro" aniolanzamiento="2020">
        <interpretes>
            <interprete>
                <nombre>Siddharta</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Rul Velazquez</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Siddharta</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 3 -->
    <cancion nombre="Si en tu mente estuve" duracion="3:11 min" genero="rock" album="los alpes" aniolanzamiento="2020">
        <interpretes>
            <interprete>
                <nombre>Nsqk</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Nsqk</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Rodrigo Torres de la Garza</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 4 -->
    <cancion nombre="Flaco" duracion="4:16 min" genero="rock" album="la trenza" aniolanzamiento="2018">
        <interpretes>
            <interprete>
                <nombre>Mon Laferte</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Mon Laferte</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Mon Laferte</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 5 -->
    <cancion nombre="Pelicula" duracion="4:56 min" genero="rap alternativo" album="Pelicula" aniolanzamiento="2018">
        <interpretes>
            <interprete>
                <nombre>Sabino</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Pablo Castañeda Amutio</nombre>
            </compositor>
            <compositor>
                <nombre>Daniel Salazar Garcia</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Pablo Castañeda Amutio</nombre>
            </letrista>
            <letrista>
                <nombre>Daniel Salazar Garcia</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 6 -->
    <cancion nombre="Dopamina" duracion="3:16 min" genero="pop" album="Belinda" aniolanzamiento="2009">
        <interpretes>
            <interprete>
                <nombre>Belinda</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Belinda</nombre>
            </compositor>
            <compositor>
                <nombre>Jorgen Ringqvist</nombre>
            </compositor>
            <compositor>
                <nombre>D. Barkman</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Belinda</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 7 -->
    <cancion nombre="Mi fiesta" duracion="3:12 min" genero="rock alternativo" album="ep" aniolanzamiento="2020">
        <interpretes>
            <interprete>
                <nombre>Bandalos Chinos</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Gregorio Degano</nombre>
            </compositor>
            <compositor>
                <nombre>Tomas Verduga</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Gregorio Degano</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 8 -->
    <cancion nombre="Tangerine" duracion="3:21 min" genero="pop" album="Damiano David" aniolanzamiento="2025">
        <interpretes>
            <interprete>
                <nombre>Damiano David</nombre>
                <alias>d4dv</alias>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Damiano David</nombre>
            </compositor>
            <compositor>
                <nombre>Amy Allen</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Damiano David</nombre>
            </letrista>
            <letrista>
                <nombre>Amy Allen</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 9 -->
    <cancion nombre="Es verdad" duracion="2:41 min" genero="Bolero" album="Boleros" aniolanzamiento="2024">
        <interpretes>
            <interprete>
                <nombre>Daniel, me estas matando</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Daniel Zepeda</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Daniel Zepeda</nombre>
            </letrista>
        </letristas>
    </cancion>

    <!-- cancion 10 -->
    <cancion nombre="Kintsugi" duracion="3:57 min" genero="rock" album="Kintsugi" aniolanzamiento="2024">
        <interpretes>
            <interprete>
                <nombre>Humbe</nombre>
            </interprete>
        </interpretes>
        <compositores>
            <compositor>
                <nombre>Humberto Rodriguez Terrazas</nombre>
            </compositor>
            <compositor>
                <nombre>Nicollas de la Espriella</nombre>
            </compositor>
        </compositores>
        <letristas>
            <letrista>
                <nombre>Humberto Rodriguez Terrazas</nombre>
            </letrista>
            <letrista>
                <nombre>Nicollas de la Espriella</nombre>
            </letrista>
        </letristas>
    </cancion>
</playlist>
